## Feature Engineering : Customer Segments

In [64]:
import numpy as np
import pandas as pd
import sklearn.preprocessing as preprocessing
import sklearn.model_selection as model_selection
import sklearn.metrics as metrics
import sklearn
import sklearn.cluster as cluster
from sklearn.datasets import make_blobs
from sklearn.preprocessing import StandardScaler
from sklearn import preprocessing, svm
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [115]:
df = pd.read_excel('dataset_complete_cluster.xlsx')
df

car_ID  symboling                   CarName fueltype aspiration  \
0         1          3        alfa-romero giulia      gas        std   
1         2          3       alfa-romero stelvio      gas        std   
2         3          1  alfa-romero Quadrifoglio      gas        std   
3         4          2               audi 100 ls      gas        std   
4         5          2                audi 100ls      gas        std   
..      ...        ...                       ...      ...        ...   
200     201         -1           volvo 145e (sw)      gas        std   
201     202         -1               volvo 144ea      gas      turbo   
202     203         -1               volvo 244dl      gas        std   
203     204         -1                 volvo 246   diesel      turbo   
204     205         -1               volvo 264gl      gas      turbo   

    doornumber      carbody drivewheel enginelocation  wheelbase  ...  \
0          two  convertible        rwd          front       88.6  ...   
1          two  convertible        rwd          front       88.6  ...   
2          two    hatchback        rwd          front       94.5  ...   
3         four        sedan        fwd          front       99.8  ...   
4         four        sedan        4wd          front       99.4  ...   
..         ...          ...        ...            ...        ...  ...   
200       four        sedan        rwd          front      109.1  ...   
201       four        sedan        rwd          front      109.1  ...   
202       four        sedan        rwd          front      109.1  ...   
203       four        sedan        rwd          front      109.1  ...   
204       four        sedan        rwd          front      109.1  ...   

     peakrpm  citympg  highwaympg    price sales 2018 sales 2019  sales 2020  \
0       5000       21          27  13495.0    34300.0    18294.0     17200.0   
1       5000       21          27  16500.0    12043.0     9444.0     10282.0   
2       5000       19          26  16500.0    17075.0    10932.0      7436.0   
3       5500       24          30  13950.0        0.0        0.0         0.0   
4       5500       18          22  17450.0        0.0        0.0         0.0   
..       ...      ...         ...      ...        ...        ...         ...   
200     5400       23          28  16845.0        0.0        0.0         0.0   
201     5300       19          25  19045.0        0.0        0.0         0.0   
202     5500       18          23  21485.0        0.0        0.0         0.0   
203     4800       26          27  22470.0        0.0        0.0         0.0   
204     5400       19          25  22625.0        0.0        0.0         0.0   

    sales 2021  total sales     cluster  
0      18252.0        88046  No Segment  
1      10539.0        42308  No Segment  
2       6297.0        41740   Regular I  
3          0.0            0  Regular II  
4          0.0            0      Luxury  
..         ...          ...         ...  
200        0.0            0  Regular II  
201        0.0            0      Luxury  
202        0.0            0      Luxury  
203        0.0            0  Regular II  
204        0.0            0      Luxury  

[205 rows x 32 columns]

In [116]:
df.drop('symboling', axis = 1, inplace = True)
df

car_ID                   CarName fueltype aspiration doornumber  \
0         1        alfa-romero giulia      gas        std        two   
1         2       alfa-romero stelvio      gas        std        two   
2         3  alfa-romero Quadrifoglio      gas        std        two   
3         4               audi 100 ls      gas        std       four   
4         5                audi 100ls      gas        std       four   
..      ...                       ...      ...        ...        ...   
200     201           volvo 145e (sw)      gas        std       four   
201     202               volvo 144ea      gas      turbo       four   
202     203               volvo 244dl      gas        std       four   
203     204                 volvo 246   diesel      turbo       four   
204     205               volvo 264gl      gas      turbo       four   

         carbody drivewheel enginelocation  wheelbase  carlength  ...  \
0    convertible        rwd          front       88.6      168.8  ...   
1    convertible        rwd          front       88.6      168.8  ...   
2      hatchback        rwd          front       94.5      171.2  ...   
3          sedan        fwd          front       99.8      176.6  ...   
4          sedan        4wd          front       99.4      176.6  ...   
..           ...        ...            ...        ...        ...  ...   
200        sedan        rwd          front      109.1      188.8  ...   
201        sedan        rwd          front      109.1      188.8  ...   
202        sedan        rwd          front      109.1      188.8  ...   
203        sedan        rwd          front      109.1      188.8  ...   
204        sedan        rwd          front      109.1      188.8  ...   

     peakrpm  citympg  highwaympg    price sales 2018  sales 2019 sales 2020  \
0       5000       21          27  13495.0    34300.0     18294.0    17200.0   
1       5000       21          27  16500.0    12043.0      9444.0    10282.0   
2       5000       19          26  16500.0    17075.0     10932.0     7436.0   
3       5500       24          30  13950.0        0.0         0.0        0.0   
4       5500       18          22  17450.0        0.0         0.0        0.0   
..       ...      ...         ...      ...        ...         ...        ...   
200     5400       23          28  16845.0        0.0         0.0        0.0   
201     5300       19          25  19045.0        0.0         0.0        0.0   
202     5500       18          23  21485.0        0.0         0.0        0.0   
203     4800       26          27  22470.0        0.0         0.0        0.0   
204     5400       19          25  22625.0        0.0         0.0        0.0   

     sales 2021  total sales     cluster  
0       18252.0        88046  No Segment  
1       10539.0        42308  No Segment  
2        6297.0        41740   Regular I  
3           0.0            0  Regular II  
4           0.0            0      Luxury  
..          ...          ...         ...  
200         0.0            0  Regular II  
201         0.0            0      Luxury  
202         0.0            0      Luxury  
203         0.0            0  Regular II  
204         0.0            0      Luxury  

[205 rows x 31 columns]

## K-Means algorithm to divide the cars in 5 customer segments


### one hot encoding for strings

In [17]:
onehot_encoder = preprocessing.OneHotEncoder(sparse = False)
li = onehot_encoder.fit_transform(df.iloc[:, 5].values.reshape(205, 1))
li
for i in range(5):
    df.at[:, 'body_encode_' + str(i)] = li[:, i]

array([[1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       ...,
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.]])

In [7]:
df.iloc[:, 2].values

array(['gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas',
       'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas',
       'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas',
       'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas',
       'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas',
       'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas',
       'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas',
       'diesel', 'gas', 'gas', 'diesel', 'diesel', 'diesel', 'diesel',
       'diesel', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas',
       'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas',
       'gas', 'gas', 'diesel', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas',
       'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas',
       'gas', 'gas', 'diesel', 'gas', 'diesel', 'gas', 'diesel', 'gas',
       'diesel', 'gas', 'diesel', 'gas', 'gas', 'gas', 'gas', 'gas',
       'gas'

In [18]:
for i in range(5):
    df.at[:, 'body_encode_' + str(i)] = li[:, i]

In [21]:
df.iloc[6:]

car_ID              CarName fueltype aspiration doornumber    carbody  \
6         7           audi 100ls      gas        std       four      sedan   
7         8            audi 5000      gas        std       four      wagon   
8         9            audi 4000      gas      turbo       four      sedan   
9        10  audi 5000s (diesel)      gas      turbo        two  hatchback   
10       11             bmw 320i      gas        std        two      sedan   
..      ...                  ...      ...        ...        ...        ...   
200     201      volvo 145e (sw)      gas        std       four      sedan   
201     202          volvo 144ea      gas      turbo       four      sedan   
202     203          volvo 244dl      gas        std       four      sedan   
203     204            volvo 246   diesel      turbo       four      sedan   
204     205          volvo 264gl      gas      turbo       four      sedan   

    drivewheel enginelocation  wheelbase  carlength  ...  sales 2019  \
6          fwd          front      105.8      192.7  ...         0.0   
7          fwd          front      105.8      192.7  ...         0.0   
8          fwd          front      105.8      192.7  ...         0.0   
9          4wd          front       99.5      178.2  ...         0.0   
10         rwd          front      101.2      176.8  ...    124537.0   
..         ...            ...        ...        ...  ...         ...   
200        rwd          front      109.1      188.8  ...         0.0   
201        rwd          front      109.1      188.8  ...         0.0   
202        rwd          front      109.1      188.8  ...         0.0   
203        rwd          front      109.1      188.8  ...         0.0   
204        rwd          front      109.1      188.8  ...         0.0   

     sales 2020  sales 2021 fuel_encoding_1 fuel_encoding_2  body_encode_0  \
6           0.0         0.0             0.0             1.0            0.0   
7           0.0         0.0             0.0             1.0            0.0   
8           0.0         0.0             0.0             1.0            0.0   
9           0.0         0.0             0.0             1.0            0.0   
10     118369.0    113209.0             0.0             1.0            0.0   
..          ...         ...             ...             ...            ...   
200         0.0         0.0             0.0             1.0            0.0   
201         0.0         0.0             0.0             1.0            0.0   
202         0.0         0.0             0.0             1.0            0.0   
203         0.0         0.0             1.0             0.0            0.0   
204         0.0         0.0             0.0             1.0            0.0   

    body_encode_1  body_encode_2  body_encode_3  body_encode_4  
6             0.0            0.0            1.0            0.0  
7             0.0            0.0            0.0            1.0  
8             0.0            0.0            1.0            0.0  
9             0.0            1.0            0.0            0.0  
10            0.0            0.0            1.0            0.0  
..            ...            ...            ...            ...  
200           0.0            0.0            1.0            0.0  
201           0.0            0.0            1.0            0.0  
202           0.0            0.0            1.0            0.0  
203           0.0            0.0            1.0            0.0  
204           0.0            0.0            1.0            0.0  

[199 rows x 36 columns]

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 31 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   car_ID            205 non-null    int64  
 1   CarName           205 non-null    object 
 2   fueltype          205 non-null    object 
 3   aspiration        205 non-null    object 
 4   doornumber        205 non-null    object 
 5   carbody           205 non-null    object 
 6   drivewheel        205 non-null    object 
 7   enginelocation    205 non-null    object 
 8   wheelbase         205 non-null    float64
 9   carlength         205 non-null    float64
 10  carwidth          205 non-null    float64
 11  carheight         205 non-null    float64
 12  curbweight        205 non-null    int64  
 13  enginetype        205 non-null    object 
 14  cylindernumber    205 non-null    object 
 15  enginesize        205 non-null    int64  
 16  fuelsystem        205 non-null    object 
 1

### making blobs for K-Means

In [27]:
features, true_labels = make_blobs(
    n_samples=205,
    centers=5,
    cluster_std=2.75,
    random_state=42
)

In [28]:
features

array([[-1.51535971e+00,  1.32438867e+01],
       [ 3.97924115e+00,  1.06868580e+00],
       [-6.16170926e+00,  9.55565453e+00],
       [ 7.94355199e+00,  2.05124576e+00],
       [-5.46328021e+00, -5.46719823e+00],
       [-8.64637202e+00,  6.26391052e+00],
       [ 2.48593228e+00,  1.08750051e+00],
       [-8.17743982e+00, -3.88549545e+00],
       [-6.75430463e+00, -8.67201055e+00],
       [ 6.07521814e+00,  2.78987754e+00],
       [ 4.65786264e-02,  3.57447189e+00],
       [ 2.69595831e+00,  2.76735782e+00],
       [ 5.32873417e+00,  2.92590226e+00],
       [-6.60295693e+00,  9.05500223e+00],
       [-9.25573677e+00,  8.94139523e+00],
       [-1.15374765e+01,  8.59430747e+00],
       [ 4.63596579e+00,  2.57496650e+00],
       [-5.35432210e+00,  5.37743189e+00],
       [-5.89571195e+00, -5.33795215e+00],
       [-2.26981819e+00,  8.19201591e+00],
       [ 2.35311322e+00,  5.57615835e+00],
       [-6.57513310e+00,  7.03471456e+00],
       [-5.65352285e+00,  9.50059532e+00],
       [-5.

In [29]:
kmeans = cluster.KMeans(
    init="random",
    n_clusters=5,
    n_init=10,
    max_iter=300,
    random_state=42
)

### making the list for all 205 cars, taking into account the average of city and highway mileage, horsepower, price and carbody type

In [34]:
features = [[0, 0, 0, 0, 0, 0, 0, 0] for i in range(205)]
# print(len(features))
for i in range(205):
    features[i][0] = (df.iat[i, 22] + df.iat[i, 23]) / 2 # mileage
    features[i][1] = df.iat[i, 20] # horsepower
    features[i][2] = df.iat[i, 24] # price
    features[i][3] = df.iat[i, 31] # convertible
    features[i][4] = df.iat[i, 32] # hardtop
    features[i][5] = df.iat[i, 33] # hatchback
    features[i][6] = df.iat[i, 34] # sedan
    features[i][7] = df.iat[i, 35] # wagon
features

[[24.0, 111, 13495.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [24.0, 111, 16500.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [22.5, 154, 16500.0, 0.0, 0.0, 1.0, 0.0, 0.0],
 [27.0, 102, 13950.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [20.0, 115, 17450.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [22.0, 110, 15250.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [22.0, 110, 17710.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [22.0, 110, 18920.0, 0.0, 0.0, 0.0, 0.0, 1.0],
 [18.5, 140, 23875.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [19.0, 160, 17859.167, 0.0, 0.0, 1.0, 0.0, 0.0],
 [26.0, 101, 16430.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [26.0, 101, 16925.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [24.5, 121, 20970.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [24.5, 121, 21105.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [22.5, 121, 24565.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [19.0, 182, 30760.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [19.0, 182, 41315.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [17.5, 182, 36880.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [50.0, 48, 5151.0, 0.0, 0.0, 1.0, 0.0, 0.0],
 [40.5, 70, 6295.0, 0.0, 0.0, 1.0, 0.0, 0.0],
 [40.5, 70, 6575.0, 0.0, 0.0, 0.0, 1.0, 0.

### scaling the features before running k-means

In [36]:
scaler = StandardScaler()
scaled_features = scaler.fit_transform(features)

In [38]:
scaled_features

array([[-0.59932483,  0.17448278,  0.02739114, ..., -0.7200823 ,
        -0.93847426, -0.372678  ],
       [-0.59932483,  0.17448278,  0.4044611 , ..., -0.7200823 ,
        -0.93847426, -0.372678  ],
       [-0.82489691,  1.26453643,  0.4044611 , ...,  1.38873015,
        -0.93847426, -0.372678  ],
       ...,
       [-1.12565968,  0.75753473,  1.02998314, ..., -0.7200823 ,
         1.06555932, -0.372678  ],
       [-0.22337137,  0.04773235,  1.15358178, ..., -0.7200823 ,
         1.06555932, -0.372678  ],
       [-0.9000876 ,  0.25053303,  1.17303131, ..., -0.7200823 ,
         1.06555932, -0.372678  ]])

### running k-means

In [39]:
kmeans.fit(scaled_features)

KMeans(init='random', n_clusters=5, random_state=42)

### these centers are the random 5 random centroids chosen by k-means algorithm

In [40]:
kmeans.cluster_centers_

array([[ 0.22445554, -0.181164  , -0.4198998 , -0.17363972, -0.20151709,
         1.38873015, -0.93847426, -0.372678  ],
       [ 0.42581024, -0.46748134, -0.34980076, -0.17363972, -0.20151709,
        -0.7200823 ,  1.06555932, -0.372678  ],
       [-0.19225798, -0.14545277, -0.1652436 , -0.17363972,  0.51074159,
        -0.7200823 , -0.93847426,  2.26176991],
       [-0.71211087,  0.69838453,  1.08086562,  5.75905085, -0.20151709,
        -0.7200823 , -0.93847426, -0.372678  ],
       [-1.14991474,  1.4689726 ,  1.66761003, -0.17363972,  0.46478941,
        -0.58402988,  0.67768185, -0.372678  ]])

### kmeans labels represent the labels assigned to each car, each label corresponds to one customer segment

In [42]:
kmeans.labels_

array([3, 3, 0, 1, 4, 1, 1, 2, 4, 0, 1, 1, 4, 4, 4, 4, 4, 4, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 2, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 4, 4, 4, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 4,
       1, 4, 2, 4, 4, 4, 3, 4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 2, 1, 0, 1, 2, 2, 0, 1, 4, 2, 4, 0, 4, 0, 1, 1, 2,
       2, 1, 1, 2, 2, 1, 1, 4, 0, 0, 0, 1, 1, 2, 0, 0, 4, 4, 3, 4, 2, 0,
       0, 1, 0, 1, 0, 4, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 0, 0, 0, 2,
       2, 2, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 2, 2, 0, 2, 0, 3, 1, 1, 0,
       1, 0, 0, 0, 4, 2, 1, 1, 1, 1, 1, 1, 1, 3, 0, 1, 1, 2, 1, 2, 1, 2,
       4, 2, 1, 4, 4, 1, 4], dtype=int32)

In [46]:
df.at[:, 'cluster'] = kmeans.labels_

In [47]:
df

car_ID  symboling                   CarName fueltype aspiration  \
0         1          3        alfa-romero giulia      gas        std   
1         2          3       alfa-romero stelvio      gas        std   
2         3          1  alfa-romero Quadrifoglio      gas        std   
3         4          2               audi 100 ls      gas        std   
4         5          2                audi 100ls      gas        std   
..      ...        ...                       ...      ...        ...   
200     201         -1           volvo 145e (sw)      gas        std   
201     202         -1               volvo 144ea      gas      turbo   
202     203         -1               volvo 244dl      gas        std   
203     204         -1                 volvo 246   diesel      turbo   
204     205         -1               volvo 264gl      gas      turbo   

    doornumber      carbody drivewheel enginelocation  wheelbase  ...  \
0          two  convertible        rwd          front       88.6  ...   
1          two  convertible        rwd          front       88.6  ...   
2          two    hatchback        rwd          front       94.5  ...   
3         four        sedan        fwd          front       99.8  ...   
4         four        sedan        4wd          front       99.4  ...   
..         ...          ...        ...            ...        ...  ...   
200       four        sedan        rwd          front      109.1  ...   
201       four        sedan        rwd          front      109.1  ...   
202       four        sedan        rwd          front      109.1  ...   
203       four        sedan        rwd          front      109.1  ...   
204       four        sedan        rwd          front      109.1  ...   

     horsepower  peakrpm  citympg  highwaympg    price sales 2018  sales 2019  \
0           111     5000       21          27  13495.0    34300.0     18294.0   
1           111     5000       21          27  16500.0    12043.0      9444.0   
2           154     5000       19          26  16500.0    17075.0     10932.0   
3           102     5500       24          30  13950.0        0.0         0.0   
4           115     5500       18          22  17450.0        0.0         0.0   
..          ...      ...      ...         ...      ...        ...         ...   
200         114     5400       23          28  16845.0        0.0         0.0   
201         160     5300       19          25  19045.0        0.0         0.0   
202         134     5500       18          23  21485.0        0.0         0.0   
203         106     4800       26          27  22470.0        0.0         0.0   
204         114     5400       19          25  22625.0        0.0         0.0   

    sales 2020  sales 2021  cluster  
0      17200.0     18252.0        3  
1      10282.0     10539.0        3  
2       7436.0      6297.0        0  
3          0.0         0.0        1  
4          0.0         0.0        4  
..         ...         ...      ...  
200        0.0         0.0        1  
201        0.0         0.0        4  
202        0.0         0.0        4  
203        0.0         0.0        1  
204        0.0         0.0        4  

[205 rows x 31 columns]

### storing in an excel file

In [48]:
df.to_excel('dataset_complete_cluster.xlsx')